version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: validador-postgres
    restart: always
    environment:
      POSTGRES_DB: validador_db
      POSTGRES_USER: validador_user
      POSTGRES_PASSWORD: Cefeid@s1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  pgdata:

